let adınız = "altug";
let soyadınız = "erbas";
let yasınız = "19";
let dogumtarihi = "2006";
let ikametedilensehir = "ankara";
let medenidurumunuz = "evli";
let mesleğiniz = "yazılımcı";
let hobiler = ["spor" , "vscode" , "DJ'lik" , ];
console.log("tesekkurler");
console.log(adınız + " " + soyadınız + " " + yasınız + " " + dogumtarihi + " " + ikametedilensehir + " " + medenidurumunuz + " " + mesleğiniz + " " + hobiler);
