let adınız = "altug";
let soyadınız = "erbas";
let yasınız = "19";
let dogumtarihi = "2006";
let ikametedilensehir = "ankara";
let medenidurumunuz = "evli";
let mesleğiniz = "yazılımcı";
let hobiler = ["spor" , "vscode" , "DJ'lik" , ];
console.log(adınız);
console.log(soyadınız);
console.log(yasınız);
console.log(dogumtarihi);
console.log(ikametedilensehir);
console.log(medenidurumunuz);
console.log(mesleğiniz);
console.log(hobiler);
console.log("tesekkurler");
console.log("benim bilgilerim" + adınız + " " + soyadınız + " " + yasınız + " " + dogumtarihi + " " + ikametedilensehir + " " + medenidurumunuz + " " + mesleğiniz + " " + hobiler);